name: Builders-Utilities
version: "${version}"
api-version: 1.13
main: net.arcaniax.buildersutilities.BuildersUtilities
authors: [ Ktar5, Arcaniax ]
website: "https://www.spigotmc.org/resources/42361/"
commands:
  butil:
    aliases: bu
    description: opens toggle menu
  banner:
    description: opens banner creator
    aliases: bm
  armorcolor:
    description: opens armor color creator
    aliases: color
  nc:
    aliases: noclip
    description: Toggles NoClip.
  af:
    aliases: advfly
    description: Toggles Advanced fly.
  n:
    aliases: nv
    description: Toggles Nightvision.
  /1:
    description: alias
  /2:
    description: alias
  /r:
    description: alias
  /s:
    description: alias
  /c:
    description: alias
  /f:
    description: alias
  /pa:
    description: alias
  /derot:
    description: alias
  /twist:
    description: alias
  /scale:
    description: alias
  /copy:
    description: alias
  /cuboid:
    description: alias
    aliases: /cub
  /flip:
    description: alias
  /convex:
    description: alias
    aliases: /con
  blocks:
    description: Opens secret blocks menu
    aliases: secretblocks
  ws:
    description: alias
  fs:
    description: alias
  bu help:
    description: Help command

permissions:
  builders.util.trapdoor:
    default: true
  builders.util.slabs:
    default: true
  builders.util.terracotta:
    default: true
  builders.util.nightvision:
    default: op
  builders.util.noclip:
    default: op
  builders.util.advancedfly:
    default: op
